
role: avatar

avatar_config_temp:
  sim_config: "../config/sim_config_franka_desk.yaml"
  robot_config: "../config/robot_config_desk_local.yaml"
  streamer_config: "../config/pipeline_config_local_desk.yaml"

twin_config:
  sim_config: "../config/sim_config_twin_franka_desk.yaml"
  robot_config: "../config/robot_config_desk_remote.yaml"
  streamer_config: "../config/pipeline_config_local_desk.yaml"
  reconciler_config: "../config/reconciler_config.yaml"
  transmission_overlay: "../config/robot_config_twin_overlay_desk.yaml"
  streamer_overlay: "../config/pipeline_config_twin_desk_overlay_local.yaml"


twin_config_temp:
  sim_config: "../config/sim_config_franka.yaml"
  robot_config: "../config/robot_config_local.yaml"
  streamer_config: "../config/pipeline_config_local.yaml"
  reconciler_config: "../config/reconciler_config.yaml"
  transmission_overlay: "../config/robot_config_twin_overlay.yaml"
  streamer_overlay: "../config/pipeline_config_twin_overlay_local.yaml"

avatar_config:
  sim_config: "../config/sim_config_franka_desk.yaml"
  robot_config: "../config/robot_config_desk_remote.yaml"
  streamer_config: "../config/pipeline_config_desk_remote.yaml"