enabled:        true
stereo:         true
stream_fps:     20
stream_width:   960  #1280
stream_height:  720 #960

stream_cameras:
  - camera:   "head_head_cam"
    shm_name: "avatar_cam"
    eye:      "mono"
  - camera:   "head_head_cam_left"
    shm_name: "avatar_cam_left"
    eye:      "left"
  - camera:   "head_head_cam_right"
    shm_name: "avatar_cam_right"
    eye:      "right"
  - camera:   "camera_right_rgb"
    shm_name: "avatar_wrist_cam_right"
    eye:      "aux"
    width:    640
    height:   480
  - camera:   "camera_left_rgb"
    shm_name: "avatar_wrist_cam_left"
    eye:      "aux"
    width:    640
    height:   480
  - camera:   "workspace_overview"
    shm_name: "avatar_overview_cam"
    eye:      "aux"
    width:    640
    height:   480

episode_listener_port: 7100

cameras:
  - name:         "head_cam"
    eye:          "mono"
    source_type:  "mujoco"
    shm_name:     "avatar_cam"
    fps:           20
    source_width:  960
    source_height: 720
    realsense_serial: ""

    stream:
      enabled:            false
      host:               "127.0.0.1"
      port:               5004
      feedback_port:      5005
      status_port:        5007
      status_interval_ms: 500
      bitrate_kbps:       4000
      fec_percentage:     10
      width:              1280
      height:             960

    log:
      enabled:    false
      output_dir: "logs"
      width:      640
      height:     480

  - name:         "wrist_cam_right"
    eye:          "aux"
    source_type:  "mujoco"
    shm_name:     "avatar_wrist_cam_right"
    fps:          20
    source_width:  640
    source_height: 480
    realsense_serial: ""

    stream:
      enabled:            true
      host:               "127.0.0.1"
      port:               5010
      feedback_port:      5011
      status_port:        5012
      status_interval_ms: 500
      bitrate_kbps:       1500
      fec_percentage:     10
      width:              640
      height:             480

    log:
      enabled:    true
      output_dir: "logs"
      width:      320
      height:     240

  - name:         "wrist_cam_left"
    eye:          "aux"
    source_type:  "mujoco"
    shm_name:     "avatar_wrist_cam_left"
    fps:          20
    source_width:  640
    source_height: 480
    realsense_serial: ""

    stream:
      enabled:            true
      host:               "127.0.0.1"
      port:               5013
      feedback_port:      5014
      status_port:        5015
      status_interval_ms: 500
      bitrate_kbps:       1500
      fec_percentage:     10
      width:              640
      height:             480

    log:
      enabled:    true
      output_dir: "logs"
      width:      320
      height:     240

  - name:         "overview_cam"
    eye:          "aux"
    source_type:  "mujoco"
    shm_name:     "avatar_overview_cam"
    fps:          20
    source_width:  640
    source_height: 480
    realsense_serial: ""

    stream:
      enabled:            false
      host:               "127.0.0.1"
      port:               5016
      feedback_port:      5017
      status_port:        5018
      status_interval_ms: 500
      bitrate_kbps:       1500
      fec_percentage:     10
      width:              640
      height:             480

    log:
      enabled:    true
      output_dir: "logs"
      width:      640
      height:     480

  - name:              "head_cam_stereo"
    eye:               "stereo"
    source_type:       "mujoco"
    shm_name:          "avatar_cam_left"
    stereo_combined:   true
    stereo_partner_shm: "avatar_cam_right"
    fps:               20
    source_width:      960
    source_height:     720
    realsense_serial:  ""

    stream:
      enabled:            true
      host:               "127.0.0.1"
      port:               5004
      feedback_port:      5005
      status_port:        5007
      status_interval_ms: 500
      bitrate_kbps:       3500   #6000
      fec_percentage:     10
      width:              1920      #2560
      height:             720     # 960

    log:
      enabled:    true
      output_dir: "logs"
      width:      640
      height:     480
