episode_listener_port: 8100   # base: 7100

stream_cameras:
  - camera:   "desk_cam"
    shm_name: "avatar_cam_twin"   # base: avatar_cam

cameras:
  - name:     "desk_cam"
    shm_name: "avatar_cam_twin"   # base: avatar_cam
    stream:
      port:          5904   # base: 5004
      feedback_port: 5905   # base: 5005
      status_port:   5907   # base: 5007
