episode_listener_port: 8100

stream_cameras:
  - camera:   "desk_cam"
    shm_name: "avatar_cam_twin"

cameras:
  - name:     "desk_cam"
    shm_name: "avatar_cam_twin"
    stream:
      port:          5904
      feedback_port: 5905
      status_port:   5907
