avatar:
  loop_rate_hz: 100
  transmission:
    send_port:    8900
    receive_port: 7900
  pipeline_logger:
    port: 8100

devices:
  - name: arm_left
    transmission:
      send_port:    8901
      receive_port: 7901

  - name: arm_right
    transmission:
      send_port:    8902
      receive_port: 7902

  - name: head
    transmission:
      send_port:    8903
      receive_port: 7903

  - name: hand_left
    transmission:
      send_port:    8904
      receive_port: 7904

  - name: hand_right
    transmission:
      send_port:    8905
      receive_port: 7905
