avatar:
  loop_rate_hz: 100
  transmission:
    send_port:    8900
    receive_port: 7900
  pipeline_logger:
    port: 8100

devices:
  - name: arm_left
    transmission:
      send_port:    8901   # base: 8001
      receive_port: 7901   # base: 7001
